<%@ Page Language="C#" MasterPageFile="~/Home.master" AutoEventWireup="true" CodeFile="About.aspx.cs" Inherits="About" Title="Untitled Page" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .style2
        {
            text-align: justify;
        }
        .style4
        {
            color: #339933;
            font-weight: bold;
            font-size: large;
        }
        .style5
        {
            color: #666633;
            font-weight: bold;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div aligin=center class="style2">
<br />
<center class="style4">About Us </center>
<br />
    <span class="style5">This is an innovative project for the field of web usage.  The main feature of our project is to analyze the most popular product as well as favorite among the peoples. In the existing system this process is done by the Customer Relation Management. They get the details among the customers and the voting is done through manually. It is a paper work. Based on the customer selection the report will be generated by the CRM department. It is long process and it takes more time to analyze the product. There can be possibility of invalid votes.
    </span>
    <br class="style5" />
    <br class="style5" />
    <span class="style5">In our proposed system the list of products will be available in the online. The user can do the registration process and they can vote for the favorite product. Once the voting process is completed the report will be generated at the same time. The products with the maximum vote are regarded as a favorite among the peoples. It saves time, avoid error in counting and there will be no invalid votes. It makes the voting process easy and it will be effective manner.</span>


</div>
</asp:Content>

